# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

import json
import logging
import os
import subprocess
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path

import jubilant
import pytest
from helpers import add_machine

logger = logging.getLogger(__name__)


LOCAL_FILESYSTEM_CLIENT = (
    Path(filesystem_client)
    if (filesystem_client := os.getenv("LOCAL_FILESYSTEM_CLIENT"))
    else None
)
LOCAL_NFS_SERVER_PROXY = (
    Path(nfs_server_proxy) if (nfs_server_proxy := os.getenv("LOCAL_NFS_SERVER_PROXY")) else None
)
LOCAL_CEPHFS_SERVER_PROXY = (
    Path(cephfs_server_proxy)
    if (cephfs_server_proxy := os.getenv("LOCAL_CEPHFS_SERVER_PROXY"))
    else None
)
LOCAL_LUSTRE_SERVER_PROXY = (
    Path(lustre_server_proxy)
    if (lustre_server_proxy := os.getenv("LOCAL_LUSTRE_SERVER_PROXY"))
    else None
)
LOCAL_LUSTRE_SERVER = (
    Path(lustre_server) if (lustre_server := os.getenv("LOCAL_LUSTRE_SERVER")) else None
)


def pytest_addoption(parser: pytest.Parser) -> None:
    parser.addoption(
        "--charm-base",
        action="store",
        default="ubuntu@26.04",
        help="Charm base version to use for integration tests",
    )
    parser.addoption(
        "--keep-models",
        action="store_true",
        default=False,
        help="Keep temporary Juju models after tests complete",
    )
    parser.addoption(
        "--run-lustre",
        action="store_true",
        default=False,
        help="run Lustre tests (slow)",
    )


def pytest_configure(config):
    config.addinivalue_line("markers", "lustre: marks tests for Lustre")


def pytest_collection_modifyitems(config, items):
    if config.getoption("--run-lustre"):
        # Flag given in cli: do not skip tests
        return
    skip_lustre = pytest.mark.skip(reason="need --run-lustre option to run")
    for item in items:
        if "lustre" in item.keywords:
            item.add_marker(skip_lustre)


@pytest.fixture(scope="session")
def juju(request: pytest.FixtureRequest) -> Iterator[jubilant.Juju]:
    """Create a temporary Juju model for the test session."""
    keep_models = bool(request.config.getoption("--keep-models"))
    with jubilant.temp_model(
        keep=keep_models, config={"update-status-hook-interval": "1m"}
    ) as juju:
        # patch up the LXD profile generated by Juju to disable secureboot
        model_name = juju.model.split(":")[-1]
        lxd_profile = f"juju-{model_name}"
        result = subprocess.check_output(
            ["lxc", "profile", "list", "--all-projects", "--format", "json"], text=True
        )
        profiles = json.loads(result)

        target = next(
            (
                (profile.get("project"), profile.get("name"))
                for profile in profiles
                if profile.get("name").startswith(lxd_profile)
            ),
            None,
        )
        if not target:
            profiles = (f"{p.get('name')} ({p.get('project')})" for p in profiles)
            pytest.fail(
                f"Could not find an LXD project containing the profile '{lxd_profile}'. "
                f"Available profiles: {', '.join(profiles)}"
            )

        cmd = [
            "lxc",
            "profile",
            "--project",
            target[0],
            "set",
            target[1],
        ]
        try:
            subprocess.check_call(cmd + ["boot.mode=uefi-nosecureboot"])
        except subprocess.CalledProcessError:
            logger.warning(
                "Failed to set boot.mode=uefi-nosecureboot for LXD profile '%s'. Falling back to security.secureboot=false",
                target[0],
            )
            subprocess.check_call(cmd + ["security.secureboot=false"])

        juju.wait_timeout = 30 * 60
        yield juju
        if request.session.testsfailed:
            log = juju.debug_log(limit=3000)
            print(log, end="")


@pytest.fixture(scope="session")
def base(request: pytest.FixtureRequest) -> str:
    """Get the base to deploy the filesystem-charms charms on."""
    return request.config.getoption("--charm-base")


@pytest.fixture(scope="module")
def filesystem_client(request: pytest.FixtureRequest) -> Path | str:
    """Get filesystem-client charm to use for integration tests.

    If the `LOCAL_FILESYSTEM_CLIENT` environment variable is not set,
    this will pull the charm from Charmhub instead.

    Returns:
        `Path` if "filesystem-client" is built locally. `str` otherwise.
    """
    if not LOCAL_FILESYSTEM_CLIENT:
        logger.info("pulling `filesystem-client` charm from charmhub")
        return "filesystem-client"

    logger.info("using local `filesystem-client` charm located at %s", LOCAL_FILESYSTEM_CLIENT)
    return LOCAL_FILESYSTEM_CLIENT


@pytest.fixture(scope="module")
def nfs_server_proxy(request: pytest.FixtureRequest) -> Path | str:
    """Get nfs-server-proxy charm to use for integration tests.

    If the `LOCAL_NFS_SERVER_PROXY` environment variable is not set,
    this will pull the charm from Charmhub instead.

    Returns:
        `Path` if "nfs-server-proxy" is built locally. `str` otherwise.
    """
    if not LOCAL_NFS_SERVER_PROXY:
        logger.info("pulling `nfs-server-proxy` charm from charmhub")
        return "nfs-server-proxy"

    logger.info("using local `nfs-server-proxy` charm located at %s", LOCAL_NFS_SERVER_PROXY)
    return LOCAL_NFS_SERVER_PROXY


@pytest.fixture(scope="module")
def cephfs_server_proxy(request: pytest.FixtureRequest) -> Path | str:
    """Get cephfs-server-proxy charm to use for integration tests.

    If the `LOCAL_CEPHFS_SERVER_PROXY` environment variable is not set,
    this will pull the charm from Charmhub instead.

    Returns:
        `Path` if "cephfs-server-proxy" is built locally. `str` otherwise.
    """
    if not LOCAL_CEPHFS_SERVER_PROXY:
        logger.info("pulling `cephfs-server-proxy` charm from charmhub")
        return "cephfs-server-proxy"

    logger.info(
        "using local `cephfs-server-proxy` charm located at %s",
        LOCAL_CEPHFS_SERVER_PROXY,
    )
    return LOCAL_CEPHFS_SERVER_PROXY


@pytest.fixture(scope="module")
def lustre_server_proxy(request: pytest.FixtureRequest) -> Path | str:
    """Get lustre-server-proxy charm to use for integration tests.

    If the `LOCAL_LUSTRE_SERVER_PROXY` environment variable is not set,
    this will pull the charm from Charmhub instead.

    Returns:
        `Path` if "lustre-server-proxy" is built locally. `str` otherwise.
    """
    if not LOCAL_LUSTRE_SERVER_PROXY:
        logger.info("pulling `lustre-server-proxy` charm from charmhub")
        return "lustre-server-proxy"

    logger.info(
        "using local `lustre-server-proxy` charm located at %s",
        LOCAL_LUSTRE_SERVER_PROXY,
    )
    return LOCAL_LUSTRE_SERVER_PROXY


@pytest.fixture(scope="module")
def lustre_server(request: pytest.FixtureRequest) -> Path | str:
    """Get lustre-server charm to use for integration tests.

    If the `LOCAL_LUSTRE_SERVER` environment variable is not set,
    this will pull the charm from Charmhub instead.

    Returns:
        `Path` if "lustre-server" is built locally. `str` otherwise.
    """
    if not LOCAL_LUSTRE_SERVER:
        logger.info("pulling `lustre-server` charm from charmhub")
        return "lustre-server"

    logger.info(
        "using local `lustre-server` charm located at %s",
        LOCAL_LUSTRE_SERVER,
    )
    return LOCAL_LUSTRE_SERVER


@pytest.fixture(scope="module")
def test_mount_client() -> Path:
    """Get test-mount-client charm to use for integration tests.

    The `LOCAL_TEST_MOUNT_CLIENT` environment variable must be set to
    the path of the locally-built test-mount-client charm.

    Returns:
        `Path` to the local test-mount-client charm.
    """
    path = os.getenv("LOCAL_TEST_MOUNT_CLIENT")
    if not path:
        raise RuntimeError("TEST_MOUNT_CLIENT_DIR environment variable must be set")

    logger.info("using local `test-mount-client` charm located at %s", path)
    return Path(path)


@dataclass
class Machines:
    mounts_machine_id: int
    storage_machine_id: int


@pytest.fixture(scope="session")
def machines(juju: jubilant.Juju, base: str) -> Machines:
    """Get the preallocated machines that can be used to deploy Juju applications.

    Returns:
        `Machines` instance containing the IDs of the deployed machines.
    """
    storage_machine_id = add_machine(
        juju, "mem=8G cores=4 root-disk=40G virt-type=virtual-machine", base=base
    )
    mounts_machine_id = add_machine(juju, "mem=8G cores=4 virt-type=virtual-machine", base=base)

    return Machines(storage_machine_id=storage_machine_id, mounts_machine_id=mounts_machine_id)
